server:
  port: 7978
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5434/demo?searchpath=notification_schema,public
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: notification_schema
  liquibase:
    enabled: true
    change-log: "classpath:/changelog/db.changelog-master.xml"
    default-schema: notification_schema
springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
logging:
  level:
    com.example.notification: DEBUG