server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
logging:
  level:
    com.example.demo: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info