apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-health
  template:
    metadata:
      labels:
        app: my-app-health
    spec:   
      containers:
        - name: health-app
          image: ubahhukob/health:latest
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 180
            timeoutSeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8000
            initialDelaySeconds: 180
            timeoutSeconds: 120
            periodSeconds: 60
            successThreshold: 2
            failureThreshold: 2