apiVersion: v1
kind: ConfigMap
metadata:
  name: health-app-config
  namespace: ubahhukob
data:
  application.yaml: |
    server:
      port: 8000
      servlet:
        context-path: /demo-service
    spring:
      datasource:
        url: jdbc:postgresql://my-postgres-postgresql:5432/postgres
        driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
          ddl-auto: none
      liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
    springdoc:
      writer-with-order-by-keys: true
      api-docs:
        path: /api-docs
        groups:
          enabled: true
    logging:
      level:
        com.example.demo: DEBUG
    management:
      endpoints:
        web:
          exposure:
            include: health,info