apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  #namespace: ubahhukob
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth-service.default.svc.cluster.local:7999/auth-service/login"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /notification-service
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 7978
      - path: /billing-service
        pathType: Prefix
        backend:
          service:
            name: billing-service
            port:
              number: 7979
      - path: /order-service
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 7976