apiVersion: v1
kind: ConfigMap
metadata:
  name: order-app-config
  namespace: ubahhukob
data:
  application.yaml: |
    server:
      port: 7976
      servlet:
        context-path: /order-service
    app:
      integration:
        billing-service:
          url: http://billing-service:7979/billing-service
        notification-service:
          url: http://notification-service:7978/notification-service
    spring:
      application:
        name: order-service
      datasource:
        url: jdbc:postgresql://my-postgres-postgresql:5432/postgres?searchpath=order_schema,public
        driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            default_schema: order_schema
      liquibase:
        enabled: true
        change-log: "classpath:/changelog/db.changelog-master.xml"
        default-schema: order_schema
    springdoc:
      writer-with-order-by-keys: true
      api-docs:
        path: /api-docs
        groups:
          enabled: true
    logging:
      level:
        com.example.order: DEBUG
    management:
      endpoints:
        web:
          exposure:
            include: health,info